"""Recommendation model - persisted optimization recommendations."""

from sqlalchemy import JSON, Boolean, Column, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class Recommendation(Base):
    """Stores optimization recommendations generated by the recommendations engine."""

    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, index=True)
    client_id = Column(Integer, ForeignKey("clients.id"), nullable=False, index=True)
    rule_id = Column(String, nullable=False)
    entity_type = Column(String, nullable=False)
    entity_id = Column(String, nullable=False)
    entity_name = Column(String, nullable=True)
    priority = Column(String, default="MEDIUM")
    category = Column(String, default="RECOMMENDATION")
    source = Column(String, default="PLAYBOOK_RULES", nullable=False)
    stable_key = Column(String, nullable=True, index=True)
    campaign_id = Column(Integer, nullable=True, index=True)
    ad_group_id = Column(Integer, nullable=True, index=True)
    reason = Column(Text, nullable=False)
    suggested_action = Column(Text, nullable=False)
    action_payload = Column(JSON, nullable=True)
    evidence_json = Column(JSON, nullable=True)
    impact_micros = Column(Integer, nullable=True)
    impact_score = Column(Float, nullable=True)
    confidence_score = Column(Float, nullable=True)
    risk_score = Column(Float, nullable=True)
    score = Column(Float, nullable=True)
    executable = Column(Boolean, default=False)
    expires_at = Column(DateTime, nullable=True)
    google_resource_name = Column(String, nullable=True)
    context_outcome = Column(String, nullable=True)
    blocked_reasons = Column(JSON, nullable=True)
    downgrade_reasons = Column(JSON, nullable=True)
    status = Column(String, default="pending")
    created_at = Column(DateTime, server_default=func.now())
    applied_at = Column(DateTime, nullable=True)

    client = relationship("Client")
