"""Recommendation model - persisted optimization recommendations."""

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.database import Base


class Recommendation(Base):
    """
    Stores optimization recommendations generated by recommendations engine.
    Persisted to DB (not ephemeral).
    """
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, index=True)
    client_id = Column(Integer, ForeignKey("clients.id"), nullable=False, index=True)
    rule_id = Column(String, nullable=False)            # "rule_1_waste_spend", "rule_2_low_qs" etc.
    entity_type = Column(String, nullable=False)        # keyword, campaign, search_term
    entity_id = Column(String, nullable=False)          # Google Ads entity ID
    entity_name = Column(String, nullable=True)         # Human-readable name (keyword text, search term, etc.)
    priority = Column(String, default="MEDIUM")         # HIGH, MEDIUM
    category = Column(String, default="RECOMMENDATION") # RECOMMENDATION (actionable) or ALERT (diagnostic)
    reason = Column(Text, nullable=False)               # "High spend ($50) with 0 conversions"
    suggested_action = Column(Text, nullable=False)     # JSON: {"type": "PAUSE_KEYWORD", "keyword_id": "123"}
    status = Column(String, default="pending")          # pending, applied, dismissed
    created_at = Column(DateTime, server_default=func.now())
    applied_at = Column(DateTime, nullable=True)

    # Relationships
    client = relationship("Client")
